#pragma once

// Generated by STruC++ - IEC 61131-3 Structured Text to C++ Compiler
// Do not edit this file manually.

#include "iec_types.hpp"
#include "iec_var.hpp"
#include "iec_array.hpp"
#include "iec_located.hpp"
#include "iec_std_lib.hpp"
#include "iec_enum.hpp"
#include "iec_memory.hpp"
#include "iec_string.hpp"
#include "iec_wstring.hpp"
#include <array>
#include <cstddef>
#include <string>

namespace strucpp {

class FF_DRE;
class COUNT_BR;

class FF_DRE {
public:
    // Inputs
    IEC_BOOL SET;
    IEC_BOOL D;
    IEC_BOOL CLK;
    IEC_BOOL RST;
    // Outputs
    IEC_BOOL Q;
    // Local variables
    IEC_BOOL EDGE;

    // Constructor
    FF_DRE();

    // Execute function block
    void operator()();

    virtual ~FF_DRE() = default;
};

class COUNT_BR {
public:
    // Inputs
    IEC_BOOL SET;
    IEC_BYTE IN;
    IEC_BOOL UP;
    IEC_BOOL DN;
    IEC_BYTE STEP;
    IEC_BYTE MX;
    IEC_BOOL RST;
    // Outputs
    IEC_BYTE CNT;
    // Local variables
    IEC_BOOL LAST_UP;
    IEC_BOOL LAST_DN;

    // Constructor
    COUNT_BR();

    // Execute function block
    void operator()();

    virtual ~COUNT_BR() = default;
};

IEC_INT INC(IEC_INT X, IEC_INT D, IEC_INT M);
}  // namespace strucpp