name: Test setup-strucpp Action

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: Autonomy-Logic/setup-strucpp@v1
      - run: strucpp --version
      - run: strucpp --help

  test-macos:
    runs-on: macos-15
    steps:
      - uses: Autonomy-Logic/setup-strucpp@v1
      - run: strucpp --version

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: Autonomy-Logic/setup-strucpp@v1
      - run: strucpp --version
